### ISSUE TITLE
Is it possible to use exception filters in UseMessageRetry?

### ISSUE THREAD

**Issue by mike-echo-oscar-whiskey** [MassTransit/Sample-AzureFunction#11]
I am trying to configure retries on one of my azure functions and would like to use exception filters.
Stumbled upon this example where you configure message retries.

Is it possible to also use exception filters with Azure Functions?
I tried, but failed.

**Comment by phatboyg** [comment]
You can filter the exceptions in the UseMessageRetry() configuration.

**Comment by mike-echo-oscar-whiskey** [comment]
Sorry, can or can't? You closed it as not planned.

**Comment by phatboyg** [comment]
Everything explained in the documentation for retries works in Azure Functions when defined in the consumer definition.

https://masstransit-project.com/usage/exceptions.html#retry-configuration

**Comment by mike-echo-oscar-whiskey** [comment]
OK, I will try again.
I tried using ConsumerDefinition as in your commit 20f206e plus using an overload of `AddMassTransitForAzureFunctions`, but had no success. If you say it should work then I must be doing something wrong so I will try again.

**Comment by mike-echo-oscar-whiskey** [comment]
I tried again, but I cannot get it working.
Does this work for topic subscriptions?

`context.GetRetryAttempt()` always returns zero.
Does this functionality depend on the existence of a `Fault-MassTransit` subscription?

**Comment by phatboyg** [comment]
GetRetryAttempt returns zero, but the actual log shows that it retries.

**Comment by mike-echo-oscar-whiskey** [comment]
OK, indeed retries are taking place.
Sorry, I should have been more specific.

It looks like configuration with below methods are not working:
* `IRetryConfigurator.Handle<T>();`
* `IRetryConfigurator.Ignore<T>();`

**Comment by phatboyg** [comment]
They absolutely do work. Do you have a code example that doesn't?

**Comment by mike-echo-oscar-whiskey** [comment]
I will send you an archive of my project over email.
