### ISSUE TITLE
Where is extension method AddMassTransitForAzureFunctions

### ISSUE THREAD

**Issue by petrkasnal** [MassTransit/Sample-AzureFunction#12]
Hi please i would like try azure function with mass transit but i cannot find method AddMassTransitForAzureFunctions. I use .Net 7.0 and in your example is it from this library: 

`using Microsoft.Azure.Functions.Extensions.DependencyInjection;`

But this library is mark as depreceted. On nuget server is link on Microsoft.Azure.Functions.Extensions  but there isnt this method. 
What i do bad?
Thanks

**Comment by phatboyg** [comment]
https://github.com/MassTransit/Sample-AzureFunction/blob/master/src/Sample.AzureFunction/Sample.AzureFunction.csproj#L9
