### ISSUE TITLE
Mass Transit with Isolated (.net 6.0+) Azure Function V4 – Azure Service Bus trigger

### ISSUE THREAD

**Issue by DavidColemanUK** [MassTransit/Sample-AzureFunction#13]
I was previously running a windows service, with a single consumer via Mass Transit & Azure Service Bus.  Looking at migrating it to Azure and An Azure Function looks like it would fit nicely. Especially the Isolated type with its full Dependency Injection now in place.

Isolated Functions look like the direction that Azure Functions are going. I’m after some advice as to how to run Mass Transit with Isolated Azure Functions v4 .Net6.0+, with it’s normal Host DI style.  Which looks like once the binding hands off to the consumer, that I can use Mass Transit natively (`.AddMassTransit()`), just like in a regular .Net Core app?

I’ve tried the [previous AF sample code](https://github.com/MassTransit/Sample-AzureFunction), which appears to be the same as the [current MT docs](https://masstransit.io/documentation/configuration/transports/azure-functions). Mass Transit Azure Functions docs relate to the in-process version, not the latest Isolated Functions style.  (Which uses AddMassTransitForAzureFunctions)

I came across [discussion 2501](https://github.com/MassTransit/MassTransit/discussions/2501) which looked promising, but the code from this doesn’t work either, maybe not for V4? Possibly V3 just as this [video](https://www.youtube.com/watch?v=qRTx3TrbNbU) is?  Related to that discussion, I've tried implementing as per the code in [this sample](https://github.com/MassTransit/Sample-AzureFunction/tree/v5/src/Sample.AzureFunction), but it doesn't compile in that way anymore. 

1. Is my understanding correct that `IMessageReceiver` is only for In-Process/WebJob style Azure Functions, not Isolated (which do not use webjobs)?  
2. Should I be using/injecting `IMessageReceiver`, `IReceiveEndpointDispatcher` or another?
3. What is the syntax for using a ASB queue trigger and passing to a Mass Transit Consumer?

Thanks.

**Comment by phatboyg** [comment]
Isolated version: https://github.com/MassTransit/Sample-AzureFunction/tree/v5

Isolated function: https://github.com/MassTransit/Sample-AzureFunction/blob/v5/src/Sample.AzureFunction/SubmitOrderFunctions.cs#L13

**Comment by DavidColemanUK** [comment]
Looked a lot harder and spotted there is an Extension method included with the Sample code that isn't in the main package.  
`AzureFunctionReceiveEndpointDispatcherExtensions.cs`

https://github.com/MassTransit/Sample-AzureFunction/blob/v5/src/Sample.AzureFunction/AzureFunctionReceiveEndpointDispatcherExtensions.cs
