### ISSUE TITLE
System.InvalidOperationException: The ConsumeContext was already set when using scheduler in .NET 5 / Functions

### ISSUE THREAD

**Issue by roycornelissen** [MassTransit/Sample-AzureFunction#3]
We have migrated our Azure Functions based MT applications to .NET 5, following this sample (`v5` version). It seems to work ok, except that we are getting this exception when running under load (when many messages arrive in quick succession, or e.g. when it's catching up on a backlog of messages in the queue):

```
System.InvalidOperationException: The ConsumeContext was already set.
   at MassTransit.Scoping.ScopedConsumeContextProvider.SetContext(ConsumeContext context)
   at MassTransit.ExtensionsDependencyInjectionIntegration.ScopeProviders.InternalScopeExtensions.SetCurrentConsumeContext(IServiceScope scope, ConsumeContext context)
   at MassTransit.ExtensionsDependencyInjectionIntegration.ScopeProviders.DependencyInjectionSagaRepositoryContextFactory`1.Send[T](ConsumeContext`1 context, Func`3 send)
   at MassTransit.ExtensionsDependencyInjectionIntegration.ScopeProviders.DependencyInjectionSagaRepositoryContextFactory`1.SendQuery[T](ConsumeContext`1 context, ISagaQuery`1 query, IPipe`1 next)
   at MassTransit.Saga.SagaRepository`1.SendQuery[T](ConsumeContext`1 context, ISagaQuery`1 query, ISagaPolicy`2 policy, IPipe`1 next)
   at MassTransit.Saga.Pipeline.Filters.QuerySagaFilter`2.GreenPipes.IFilter<MassTransit.ConsumeContext<TMessage>>.Send(ConsumeContext`1 context, IPipe`1 next)
   at MassTransit.Saga.Pipeline.Filters.QuerySagaFilter`2.GreenPipes.IFilter<MassTransit.ConsumeContext<TMessage>>.Send(ConsumeContext`1 context, IPipe`1 next)
   at GreenPipes.Filters.RetryFilter`1.Attempt(TContext context, RetryContext`1 retryContext, IPipe`1 next)
   at GreenPipes.Filters.RetryFilter`1.Attempt(TContext context, RetryContext`1 retryContext, IPipe`1 next)
   at GreenPipes.Filters.RetryFilter`1.GreenPipes.IFilter<TContext>.Send(TContext context, IPipe`1 next)
   at MassTransit.Pipeline.Filters.InMemoryOutboxFilter`2.Send(TContext context, IPipe`1 next)
   at MassTransit.Pipeline.Filters.InMemoryOutboxFilter`2.Send(TContext context, IPipe`1 next)
   at GreenPipes.Filters.TeeFilter`1.<>c__DisplayClass5_0.<<Send>g__SendAsync|1>d.MoveNext()
```

Any idea where to look for the cause of this? A misconfiguration on our side, or a bug in MT, or something else? Our DI setup follows the sample code in this repo.

Eventually, the retry mechanism does seem to iron everything out, but we'd rather not see this error :)

**Comment by phatboyg** [comment]
Are you consuming the same message more than once by different consumers and/or sagas within the same function trigger?

**Comment by roycornelissen** [comment]
🤔 No, not that exactly, but I did find the common theme between the two endpoints that are having this issue after migrating to .NET 5: both are using scheduled messages. One is using `context.Redeliver(...)`, and the other has a Saga that uses the scheduler for timeouts.

I am able to reproduce this with a simple FunctionApp with one Function and one Consumer that calls `context.Redeliver(...)`.

This is my sample consumer that triggers the issue:

```csharp
public async Task Consume(ConsumeContext<SampleCommand> context)
{
    // redeliver on even seconds...
    if (DateTime.Now.Second % 2 == 0)
    {
        Console.WriteLine($">>> Redeliver...");
        await context.Redeliver(TimeSpan.FromSeconds(4));
        return;
    }

    Console.WriteLine($">>> Consumed SampleCommand message with ID {context.Message.MessageId}");
}
```

We use `mt.AddServiceBusMessageScheduler()` in our DI setup.

In fact, I'm now seeing that first it throws `The payload was not found: MassTransit.MessageSchedulerContext` when `context.Redeliver()` is called, and I think that `System.InvalidOperationException: The ConsumeContext was already set.` happens upon retry of that fault. So one issue was burying the other in the output logs.

Yep... disabling retries only surfaces `The payload was not found`... Once I enable retry, the `The ConsumeContext was already set` message is added to the mix.

```csharp
mt.UsingAzureServiceBus((context, cfg) =>
{
    cfg.Host(hostContext.Configuration["AzureWebJobsServiceBus"]);
    cfg.UseInMemoryOutbox();
    cfg.UseMessageRetry(retry =>
    {
        retry.Intervals(100, 200, 500, 800, 1000);
    });
});
```

**Comment by phatboyg** [comment]
So, first off, the ordering is wrong - the outbox should be after the message retry filter. And any scheduled redelivery should be before that. And message scheduler before that one as well. 

Honestly, I don't know if bus-global configurations work with the receive endpoint dispatcher. Though if you see the retry happening, I guess they do apply.

**Comment by roycornelissen** [comment]
Hm yes indeed, somehow the pipeline definition got messed up with the conversion. I ended up having to do the following in my demo app to get it to work with message redelivery:

```
.ConfigureServices((hostContext, services) =>
{
    services
        .AddScoped<CommandsFunction>()
        .AddScoped<SecondCommandFunction>();

    services.AddMassTransit(mt =>
    {
        mt.AddConsumersFromNamespaceContaining<FirstCommandHandler>();

        mt.AddServiceBusMessageScheduler();
        mt.SetKebabCaseEndpointNameFormatter();

        mt.UsingAzureServiceBus((context, cfg) =>
        {
            cfg.UseServiceBusMessageScheduler();
            cfg.Host(hostContext.Configuration["AzureWebJobsServiceBus"]);
            cfg.UseMessageRetry(retry =>
            {
                retry.Ignore<InvalidOperationException>();
                retry.Intervals(100, 200, 500, 800, 1000);
            });
            cfg.UseInMemoryOutbox();
            cfg.ConfigureEndpoints(context);
        });
    });

    services.AddMassTransitHostedService(true);
})
```

Only, now it looks like any additional consumer+message type breaks it. Getting "Message was not consumed" upon dispatching the second message. This happens when I have 2 separate functions listening on separate queues, that take a dependency on a specific `IReceiveEndpointDispatcher<TConsumer>`, and also when I use the `IReceiveEndpointDispatcher<CatchAll>()` trick with one function and one queue.

**Comment by phatboyg** [comment]
Probably not related, but you should not be calling ConfigureEndpoints(), since you're using Azure Functions to dispatch messages to the consumers...

**Comment by roycornelissen** [comment]
Yeah, removing that breaks the redelivery of the message when the consumer calls `.Redeliver(...)`. (The message is not dispatched to the consumer anymore). But this might now conflict with the Functions based dispatching as you describe. I guess the redelivery and scheduling is now handled "internally" by MT... Could we be trying something that is impossible?

All this worked fine in a `netcoreapp3.1` based Functions app.

**Comment by phatboyg** [comment]
Well, .NET 5 function apps are completely different, nothing is the same. And the support available has very limited testing, so I'm not sure how it works with the various edge cases.

**Comment by roycornelissen** [comment]
So I notice ☹️ We're updating components to .NET5 across the board and Functions apps are the only ones causing trouble. Not sure if I can manage to keep those `netcoreapp3.1` for now. I might try that.

Many thanks though for your input and responsiveness. I'll report on further progress/findings here, or close this issue if it's a dead end.

**Comment by roycornelissen** [comment]
Just FYI, in the end I decided to host the messaging endpoints in a regular .NET 5 application (at least for the time being). I see too many issues with Azure Functions in .NET 5 in combination with MassTransit. Especially timeouts and saga's are problematic, and "generic" dispatching of messages from a Function.

Not sure if you should recommend running MassTransit like this, or at least add a big warning.

**Comment by phatboyg** [comment]
In the long run, the deployment story combined with the fact you're using a regular service with MassTransit will benefit you more than any meager savings you might get from using Azure Functions. The complexity/changes in v5 are just, well, I can appreciate the _why_ but the execution is cumbersome at this point.
