### ISSUE TITLE
Question: why use custom FunctionScope?

### ISSUE THREAD

**Issue by roycornelissen** [MassTransit/Sample-AzureFunction#4]
A question about the sample implementation in the v5 branch: in [AzureFunctionReceiveEndpointDispatcherExtensions](https://github.com/MassTransit/Sample-AzureFunction/blob/v5/src/Sample.AzureFunction/AzureFunctionReceiveEndpointDispatcherExtensions.cs), you are creating a custom `FunctionScope`. Any particular reason for this over using `context.InstanceServices.CreateScope()` ?

Thanks!

**Comment by phatboyg** [comment]
Because the scope was already created when the function was resolved, so creating another one wouldn't make any sense.

**Comment by roycornelissen** [comment]
Makes sense! Thanks!
