### ISSUE TITLE
Example does not match what is available in the latest version

### ISSUE THREAD

**Issue by norarrsgd** [MassTransit/Sample-AzureFunction#7]
In the example:
```csharp
[Function("SubmitOrder")]
public Task SubmitOrderAsync([ServiceBusTrigger(SubmitOrderQueueName, Connection = "ServiceBusConnection")] byte[] body, FunctionContext context)
{
      return _dispatcher.Dispatch(context, body);
}
```

The `_dispatcher.Dispatch` method only asks for a `FunctionContext` and `byte[]` as parameters, however in the latest version it asks for:

![image](https://user-images.githubusercontent.com/9804927/174199614-efd40bc9-87e5-4b2b-9022-999c4c7674f9.png)

I think the example should be updated to reflect these changes

**Comment by gertjvr** [comment]
Upgrade v5 to MT 8.0.3 and can't replicate the issue, also upgraded to dotnet6 and azure function  v4 and everything still works as before

**Comment by gertjvr** [comment]
and there is an extension method that resembles the `headers` but you're not forced to use it

![image](https://user-images.githubusercontent.com/1691062/174202043-0384ba76-3d48-4638-add3-3ad2b3413b44.png)

**Comment by DavidColemanUK** [comment]
I'm ran into the same confusion @kuromukira , until I found this thread.  
That `AzureFunctionReceiveEndpointDispatcherExtensions.cs` Extension file added really threw me until I spotted it!
Are there plans to include that extension in the main MassTransit package? @gertjvr

**Comment by phatboyg** [comment]
> Are there plans to include that extension in the main MassTransit package? @gertjvr

No, as it would add a dependency on Azure Functions packages, which isn't happening.
