### ISSUE TITLE
Mass Transit version

### ISSUE THREAD

**Issue by kmrritesh09** [MassTransit/Sample-AzureFunction#9]
You are using a develop version of masstransit 8.0.7-develop.575. This functionality is not supported in release version 8.0.6 of masstransit.

Any idea when the new release version will be released which will allow using azure message bus in mass transit. Thank you!

**Comment by phatboyg** [comment]
I'm not sure where you get your information from, but 8.0.6 works fine with whatever it is you're asking.

**Comment by kmrritesh09** [comment]
seems you are right. May be initially it didn't work and after I upgraded and then downgraded to release version it seems to work. Must have missed something in the beginning. Apologies for the trouble and thanks!
